name: Add issues and PRs to projects

on:
  issues:
    types:
      - opened
      - reopened
  pull_request:
    types:
      - opened
      - reopened

jobs:
  add-to-project:
    name: Add to project
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        project-url:
          - https://github.com/orgs/ACCESS-NRI/projects/27 # AMAMI
    steps:
      - uses: actions/add-to-project@244f685bbc3b7adfa8466e08b698b5577571133e # v1.0.2
        with:
          project-url: ${{ matrix.project-url }}
          github-token: ${{ secrets.ADD_TO_PROJECTS_TOKEN }}